List<String> name = [
  "Angel Wing Begonia",
  "Barberton Daisy",
  "Beach Spider Lily",
  "Belladonna Lily",
  "Bird Of Paradise",
  "Blushing Bromeliad",
  "Busy Lizzie",
  "Calla Lily",
  "Aluminum Plant",
  "Areca Palm",
  "Arrowhead",
  "Bird's Nest Fern",
  "Boston Fern",
  "Broadleaf Lady Palm",
  "Canary Date Palm",
  "Cast Iron Plant",
  "Chinese Evergreen",
  "Coral Bead",
  "Aloe Vera",
  "Argyroderma testiculare",
  "Baby Rubber Plant",
  "Bunny Ear Cactus",
  "Century Plant",
  "Christmas Cactus",
  "Christmas cheer",
  "Coral Cactus",
  "Donkeys Tail",
  "Donkeys Tail",
  "Easter Cactus"
];
List<String> desc = [
  "Bulb flowering type plants that produce a cluster of attractive trumpet like flowers in different color variations.",
  "African violet care information guide: Belonging to the Saintpaulia Genus with many species. Growing conditions, possible problems, pictures and description.",
  "This plant is from a large genus named Begonia. The Angel Wing Begonia is one of the most popular species from the genus.",
  "A flowering pot plant displaying striking flowers.",
  "This amazing bulb based plant beach spider lily enjoys environments that are downright aquatic and easy to maintain.",
  "Also known as the naked lady because of the bare flower stalks that appear without leaves.",
  "The Bird of Paradise is a delightfully easy to care for plant that enjoys warm, balmy days year round.",
  "An interesting species from the bromeliad family which produces a red center within the rosette of leaves.",
  "Grown for their attractive blooms outdoors (just about everywhere) and indoors when given enough bright light.",
  "Keeping this rhizome happy indoors is a matter of paying attention to some very basic growing conditions.",
  "An easy going house plant that is generally simple to please.",
  "A cane type palm growing up to 8ft tall with mulitple stems.",
  "Very similar species as the Philodendron and from the same family.",
  "A popular fern plant that display attractive 2 ft long fronds once it matures.",
  "One of the easier ferns to grow indoors.",
  "A popular indoor plant species which looks elegant standing in offices, hotels, living rooms and conservatories.",
  "A tough palm displaying long fronds with thin straight leaflets.",
  "Receives its common name for its ability to withstand neglect. A nice an easy to care for foliage plant.",
  "Grown primarily for the attractive leathery leaves.",
  "With its picky watering and light demands, the coral bead plant has proven difficult for beginner house plant growers.",
  "The Aloe Vera is a common house plant that has many potential heath benefits. An indoor Aloe is easy to grow and not demanding.",
  "A living stones plant that blooms a beautiful daisy like flower the end of fall - beginning of winter.",
  "Although this plant can flower its main attraction is the foliage.",
  "The bunny ear cactus, also known as the polka dot cactus is a very popular plant.",
  "A tough succulent species that's easy to grow indoors which can grow over 1m tall with large toothed leaves.",
  "The Christmas cactus is the ideal house plant if a grower likes to see flowers blooming from November - January.",
  "Very close relative to the Jelly beans plant displaying leaves which turn red in sunlight.",
  "The Coral cactus is much as the name states in one sense and not in another. It's similar looking to coral but not an actual cactus.",
  "The Donkeys tail is a trailing succulent species suitable for growing in a hanging basket.",
  "Tropical cactus that requires a certain amount of regular water in order to survive."
];
List<double> bestemp = [
  21.1111,
  20,
  18,
  24,
  32,
  25,
  25,
  27,
  22,
  27,
  28,
  23,
  29,
  30,
  17,
  25,
  30,
  19,
  27,
  15,
  45,
  19,
  23,
  33,
  24,
  20,
  0,
  20,
  24,
  15
];

List<String> photourl = [
  "image-files/hippeastrum-plant.jpg",
  "assets/images/av-blue-1.jpg",
  "assets/images/angel_wing_begonia1.jpg",
  "assets/images/gerbera_jamesonii_1.jpg",
  "assets/images/beach_spider_lily_img1.jpg",
  "image-files/amaryllis-belladonna.jpg",
  "assets/images/Strelitzia_Reginae_Flower_img1.jpg",
  "image-files/blushing_bromeliad1.jpg",
  "image-files/impatiens-walleriana-lilac.jpg",
  "image-files/calla-lily-flower.jpg",
  "image-files/aluminum_plant.jpg",
  "assets/images/areca_palm_1.jpg",
  "assets/images/syngonium_podophyllum.jpg",
  "assets/images/asplenium_nidus_attached_to_tree_1.jpg",
  "assets/images/boston_ferns_in_hanging_baskets_1.jpg",
  "image-files/broadleaf_lady_palm1.jpg",
  "image-files/canary.jpg",
  "image-files/Aspidistra_Elatior.jpg",
  "image-files/aglaonema.png",
  "assets/images/Nertera-Granadensis-1.jpg",
  "assets/images/aloe-foliage-1.jpg",
  "assets/images/argyroderma_flowering.jpg",
  "assets/images/baby_rubber_plant.jpg",
  "image-files/Opuntia-microdasys.jpg",
  "assets/images/century_plant1.jpg",
  "image-files/christmas-cactus.jpg",
  "assets/images/sedum_rubrotinctum1.jpg",
  "image-files/coral-cactus-orig.jpg",
  "assets/images/donkeys_tail_sedum.jpg",
  "image-files/Hatiora-gaertneri.jpg",
];
